### ISSUE TITLE
NoMethodErrorの対応

### ISSUE THREAD

**Issue by ktst79** [Azumaxoid/catalogue-3#1]
伊藤さんお願いします。

[catalogue-3] app/services/socks_selector.rb (Lines 15-16)

```

        |sock| @tags.find { |tag| tag == Tag.find(SockTag.find_by(sock_id: sock.sock_id).tag_id).name }

```

[Open in IDE](https://api.codestream.com/c/YWfKC5Zai0QpSpZg/5FZGuIFsS82HPCU606yYDA?marker=61e0d6cc628dc141e49df579&ide=default&src=GitHub) · [Open on GitHub](https://github.com/azumaxoid/catalogue-3/blob/07a78f080811a72cd03bc1bc32425f13f70d1255/app/services/socks_selector.rb#L15-L16)

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by qryuu** [comment]
クローズします。
